# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xuVUI8HQGY2mpJArLjgbtp1GPazxdp2V
"""

! pip install -q condacolab
import condacolab
condacolab.install()

import condacolab
condacolab.check()

!conda create -n tflite_env python=3.11

!python3.11 -m venv tflite_env
!source tflite_env/bin/activate

!pip3 install -q tflite-model-maker

!pip uninstall tensorflow -y

!pip install tensorflow==2.13.0

!pip install importlib numpy

!pip3 list | grep -i tensorflow

!pip install tflite-support-nightly

!python3 'add-tflite-metadata.py'