# -*- coding: utf-8 -*-
"""verify-tflite-metadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cMsDSA-NYJIGhr6P9myoq73xQJFIqijy
"""

! pip install -q condacolab
import condacolab
condacolab.install()

import condacolab
condacolab.check()

!conda create -n tflite_env python=3.10

!python3 -m venv tflite_env

!source tflite_env/bin/activate

!pip3 install tensorflow==2.13.0

!python3 -m pip install tflite-support-nightly

!python3 '/content/verify-tflite-metadata.py'